### ISSUE TITLE
Need more mentor requests

### ISSUE THREAD

**Issue by Balfa** [hackutd/HackUTD-Mentoring#2]
## HackUTD 16 Mentoring

The number of mentor requests is too low! 
### Steps to reproduce
- Wait for mentoring requests
- Observe that there are none
### Recommended Fix
- Make more mentor requests

**Comment by KashMoneyMillionaire** [comment]
I think this should be marked as closed. I observed this one, which seems to fix the problem: https://github.com/hackutd/HackUTD-Mentoring/issues/2
