### ISSUE TITLE
Deploy NodeJS Express application to AWS

### ISSUE THREAD

**Issue by jaybutera** [hackutd/HackUTD-Mentoring#6]
## HackUTD 16 Mentoring

Create an issue describing your problem and we'll send you a mentor to help out.
#### Tell us what language/hardware/API/library you are working with:

NodeJS, express, AWS Elastic Beanstalk
#### Describe the problem and be as detailed as possible:

After deployment, the URL just gives a 502 Bad Gateway error.
#### Tell us your location:

ECSS 2.410

**Comment by KashMoneyMillionaire** [comment]
Is this still open?

**Comment by nishitsadhwani** [comment]
Is this still open ?
I can help with deploying Node.js code , if you can share the error log.

**Comment by jaybutera** [comment]
I've passed this problem now, it was a port issue. I'm now stuck trying to
get socket.io working in ELB (possibly by using HAProxy). Any experience
with that?

Regards,
Jay Butera
