### ISSUE TITLE
Need help with reading osm.pbf file. At room 415 second row

### ISSUE THREAD

**Issue by rohanshimpi** [hackutd/HackUTD-Mentoring#8]
## HackUTD 16 Mentoring

Create an issue describing your problem and we'll send you a mentor to help out.

**Comment by whilke** [comment]
Protocol buffer file? What error? What language?

**Comment by nathanqthai** [comment]
If using Unix/OS X you can use pip to fetch the imposm module.

If using Windows, we found the best solution to be using [Osmosis](https://wiki.openstreetmap.org/wiki/Osmosis/Examples).
